### ISSUE TITLE
Creating a new region TODO list

### ISSUE THREAD

**Issue by RedSparr0w** [pokeclicker-dev/pokeclicker#49]
### New regions TODO list:

- [ ] Map
  - [ ] Create base image
  - [ ] Add routes
  - [ ] Add towns
  - [ ] Add dungeons
  - [ ] Add starter town
  - [ ] Add dock
- [ ] Map SVG
  - [ ] Add routes
  - [ ] Add towns
  - [ ] Add dungeons
  - [ ] Add starter town
    - [ ] Update GameConstants
  - [ ] Add dock
    - [ ] Update GameConstants
- [ ] Towns
  - [ ] Get list of towns
  - [ ] Get images
  - [ ] Add requirements
  - [ ] Add stores
- [ ] Gyms/Elite 4
  - [ ] List of gyms
  - [ ] List of Elite 4 members
  - [ ] Add Gym leader teams
  - [ ] Add Elite 4 teams
  - [ ] Add requirements
  - [ ] Get images
  - [ ] Adjust Pokemon HP
  - [ ] Adjust reward amounts
  - [ ] Assign an environment type
  - [ ] Badge List
  - [ ] Badge Images
- [ ] Dungeons
  - [ ] Get list of dungeons
  - [ ] Filter dungeon list
  - [ ] Add Pokemon to the dungeons
  - [ ] Add requirements
  - [ ] Get images
  - [ ] Adjust Pokemon HP
  - [ ] Adjust reward amounts
  - [ ] Assign an environment type
- [ ] Pokemon
  - [ ] Get a list of Pokemon and stats etc.
  - [ ] Get the sprites
  - [ ] Check evolutions
  - [ ] Alternative forms
    - [ ] Game Data
    - [ ] Images
- [ ] Routes
  - [ ] Add Pokemon to every route
  - [ ] Assign an environment type
  - [ ] Add route requirements
    - [ ] Routes
    - [ ] Badges
    - [ ] Dungeons
- [ ] Eggs
  - [ ] Add some Pokemon to each of the eggs
- [ ] Evolution stones
  - [ ] Do we need any new stones?
- [ ] Legendary Pokemon
  - [ ] Roaming Pokemon
  - [ ] Dungeon Pokemon
  - [ ] Other
- [ ] Playthrough
- [ ] Ensure all Pokemon can be obtained

**Comment by anapple96** [comment]
List of OK things : 

- [x] Map : All done, except the dock, still need to mess with highest regions
- [x] Legendaries : All done
- [ ] Route : 
       - [ ] Requirements - Almost done, some requirements are impossible with the current codebase

**Comment by RedSparr0w** [comment]
This is just for new regions in general, The stuff left for sinnoh is here:
https://github.com/pokeclicker-dev/pokeclicker/pull/42

**Comment by anapple96** [comment]
Oops

**Comment by anapple96** [comment]
Add thess one real quick :  
  - Under "Dungeons" : Add "Adjust Token Price" - Whoever did Hoenn forgot about this
  - Under "Gyms/Elite 4": Add "Make sure the teams match their respective teams in the game that the region is based on" - Whoever did Hoenn also forgot to do that

**Comment by RedSparr0w** [comment]
Think those come under:
 Adjust reward amounts
 Add Gym leader teams
 Add Elite 4 teams

**Comment by anapple96** [comment]
Token comes under reward?
Weiiird
